// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IconFont: typeof import('./src/components/Icon/src/IconFont.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/src/SvgIcon.vue')['default']
  }
}

export { }
